Run the Game of Life with a blinker pattern for 3 steps:
  $ dune exec -- ono concrete game.wat --config config.txt --steps 3 --speed 0 --seed 42
  .....
  .@@@.
  .....
  .....
  .....
  ..@..
  ..@..
  ..@..
  .....
  .....
  .....
  .@@@.
  .....
  .....
  .....
  OK!
