name: build-nix
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: test
        run: |
          set -x

          nix-shell --run "
            dune build @fmt &&
            dune build @doc &&
            dune build @install &&
            dune build @all &&
            dune runtest
          "

      - name: Check generated opam is up-to-date
        run: |
          set -x
          nix-shell -p git --run "git diff --exit-code ono.opam"
